### ISSUE TITLE
Retroarch cant load gambatte core

### ISSUE THREAD

**Issue by GodSponge** [libretro/gambatte-libretro#154] opened 2020-08-06 05:50 UTC
When trying to run any ROMs, I get this in the log:
D:\Games\LaunchBox\Emulators\retro arch>[INFO] RetroArch 1.8.5 (Git 532fd88e2f)
[INFO] Redirecting save file to "D:\Games\LaunchBox\Emulators\retro arch\saves\ROM.srm".
[INFO] Redirecting savestate to "D:\Games\LaunchBox\Emulators\retro arch\states\ROM.state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Mar 19 2020
[INFO] Version: 1.8.5
[INFO] Git: 532fd88e2f
[INFO] =================================================
[INFO] Loading dynamic libretro core from: ".\cores\gambatte_libretro.dll"
**[ERROR] Failed to open libretro core: "D:\Games\LaunchBox\Emulators\retro arch\cores\gambatte_libretro.dll"
Error(s): %1 is not a valid Win32 application.**

I have tried updating the core and still had the same issue. I even deleted the dll file manually and redownloaded the core from the updater and still get the same error. Loading other cores runs the games as they should.

**Comment by hizzlekizzle** [comment] 2020-08-06 15:12
Confirmed. It looks like the buildbot is pushing a 64-bit library out to the 32-bit core repository.

**Comment by twinaphex** [comment] 2021-11-03 16:16
This is fixed according to @hizzlekizzle , closing...

**Closed by twinaphex** 2021-11-03 16:16 UTC
